version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost-blog
    restart: unless-stopped
    networks:
      - ghost-net
    volumes:
      - ./ghost-content:/var/lib/ghost/content
    environment:
      url: http://localhost
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - ghost-net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  ghost-net:
    driver: bridge

